#!/bin/bash
# Extract YouTube credentials in container with bgutil available.
# Run during container startup to generate fresh tokens.
#
# Outputs /tmp/youtube_creds.sh, which can be sourced to set:
#   YTDLP_YOUTUBE_VISITOR_DATA
#   YTDLP_YOUTUBE_PO_TOKEN

set -e

echo "[INFO] Extracting YouTube credentials via yt-dlp + bgutil..."

# Create a working directory for temp files
TEMP_DIR="/tmp/yt_creds"
mkdir -p "$TEMP_DIR"
cd "$TEMP_DIR"

# "Me at the zoo" — first YouTube video; publicly accessible and stable
TEST_VIDEO="https://www.youtube.com/watch?v=jNQXAC9IVRw"

echo "[INFO] Testing yt-dlp extraction with web_safari client..."

# Run yt-dlp with verbose output; capture both stdout and stderr.
# Use web_safari since mweb is known to fail with bot-check in headless environments.
if python3 -m yt_dlp \
    --dump-json \
    --skip-download \
    -f "best" \
    --extractor-args "youtube=player_client=web_safari,pot_trace=true" \
    -v \
    "$TEST_VIDEO" > extraction.json 2> extraction.log; then

    echo "[INFO] Extraction succeeded"

    # Extract visitor data from response JSON if available
    if grep -q "visitor_data" extraction.json 2>/dev/null; then
        VISITOR_DATA=$(grep -o '"visitor_data":"[^"]*' extraction.json | head -1 | cut -d'"' -f4)
        echo "[INFO] Extracted visitor_data: $VISITOR_DATA"
    else
        # bgutil will still generate PO tokens without a pre-seeded visitor_data,
        # but supplying one improves reliability.
        VISITOR_DATA="CgtXd0NFVEhoQjFRYw%3D%3D"
        echo "[WARN] visitor_data not found in response; using fallback: $VISITOR_DATA"
    fi

    # PO tokens are generated dynamically by bgutil at runtime; no need to persist them here.
    PO_TOKEN=""
    echo "[INFO] PO token will be generated by bgutil at runtime"

else
    echo "[WARN] yt-dlp extraction failed; falling back to known-good visitor_data"
    VISITOR_DATA="CgtXd0NFVEhoQjFRYw%3D%3D"
    PO_TOKEN=""

    echo "[DEBUG] Last 50 lines of extraction log:"
    tail -50 extraction.log || true
fi

# Write credentials file that the startup entrypoint can source
CREDS_FILE="/tmp/youtube_creds.sh"
cat > "$CREDS_FILE" <<EOF
export YTDLP_YOUTUBE_VISITOR_DATA="${VISITOR_DATA}"
export YTDLP_YOUTUBE_PO_TOKEN="${PO_TOKEN}"
EOF
chmod 600 "$CREDS_FILE"

echo "[INFO] Credentials written to $CREDS_FILE"
echo "  YTDLP_YOUTUBE_VISITOR_DATA=${VISITOR_DATA}"
echo "  YTDLP_YOUTUBE_PO_TOKEN=${PO_TOKEN:-<empty, bgutil generates at runtime>}"

# Cleanup temp directory
cd /
rm -rf "$TEMP_DIR"

echo "[INFO] YouTube credential extraction complete"
